# -*- coding: utf-8 -*-
"""[AGENTE] Agente Severino

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o00dLd3blgUkNGF5gj5KNMUInnfi-iqj
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini

import os
from google.colab import userdata

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

# Configura o cliente da SDK do Gemini

from google import genai

client = genai.Client()

MODEL_ID = "gemini-2.0-flash"

# Pergunta ao Gemini uma informação mais recente que seu conhecimento

from IPython.display import HTML, Markdown

# Exibe a busca
#print(f"Busca realizada: {response.candidates[0].grounding_metadata.web_search_queries}")
# Exibe as URLs nas quais ele se baseou
#print(f"Páginas utilizadas na resposta: {', '.join([site.web.title for site in response.candidates[0].grounding_metadata.grounding_chunks])}")
#print()
#display(HTML(response.candidates[0].grounding_metadata.search_entry_point.rendered_content))

# Instalar Framework ADK de agentes do Google ################################################
!pip install -q google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
          for part in event.content.parts:
            if part.text is not None:
              final_response += part.text
              final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# --- Agente 1: Buscador de Soluções --- #
##########################################
# Inserir as instruções do Agente Buscador de Soluções #################################################
def agente_buscador(problema, data_de_hoje):
  buscador = Agent(
      name="agente_buscador",
      model="gemini-2.0-flash",
      description="Agente que busca soluções para problemas cotidianos",
      tools = [google_search],
      instruction = """
        Você é um assistente de pesquisas domésticas. A sua tarefa é usar a faerramenta de busca do google (google_search)
        para recuperar os resultados mais relevantes para solucionar os problemas pesquisados pelos usuários.
        Foque em, no máximo, 5 fontes diferentes, com na autoridade dos domínios e na quantidade de interações rastreadas para a fonte.
        Se uma fonte não for de um domínio com autoridade alta e não tiver interações rastreadas, ignore-a.
        Ao final, você escolherá a solução mais relevante entre elas com base nas suas pesquisas e irá retorná-la como
        opção mais segura.
      """
  )
  entrada_do_agente_buscador = f"Problema: {problema}\nData de hoje: {data_de_hoje}"
  solucoes = call_agent(buscador, entrada_do_agente_buscador)
  return solucoes

######################################
# --- Agente 2: Severino Resolve --- #
######################################
def agente_severino(problema, solucoes_mais_provaveis):
    severino = Agent(
        name="agente_severino",
        model="gemini-2.0-flash",
        instruction="""
            Você é um Marido de Aluguel especializado em explicar de maneira clara e com vocabulário
            acessível quais são as melhores soluções para os problemas que são buscados pelos usuários.
            Você é o Agente Severino, o melhor Marido de Aluguel Digital que existe no Brasil.
            Utilize as soluções ranqueadas pelo agende planejador e, com base nisso,
            descreva a melhor solução para o usuário. Se o usuário julgar que sua primeira resposta não foi útil,
            forneça uma segunda opção, com base na ordem criada pelo agente planejador.
            Você não deve utilizar gírias. Seu tom de voz é respeitoso, mas leve e amigável.
            Depois de enviar a resposta, você deve perguntar para o usuário se ele gostaria que você buscasse por
            prestadores de serviço que possam ajudar a resolver o problema buscado pelo usuário originalmente.
            Se o usuário disser que sim, ele deverá informar a cidade e o estado onde ele mora.
            """,
        description="Agente Marido de Aluguel que soluciona problemas cotidianos"
    )
    entrada_do_agente_severino = f"Problema: {problema}\nSoluções mais prováveis: {solucoes_mais_provaveis}"
    # Executa o agente
    solucao = call_agent(severino, entrada_do_agente_severino)
    return solucao

#######################################
# --- Agente 3: Severino Pergunta --- #
#######################################
def agente_questionador(problema, cidade, estado):
    questionador = Agent(
        name="agente_questionador",
        model="gemini-2.0-flash",
        tools = [google_search],
        instruction="""
            Você é um Marido de Aluguel que irá pesquisar prestadores de serviço utilizando a tools (google_search) para indicar ao usuário.
            Depois que ele informar a cidade o estado onde reside, você deve utilizar a tools (google_search) para buscar por profissionais
            que podem ajudar a resolver o problema que o usuário pesquisou inicialmente.
            """,
        description="Agente Marido de Aluguel que busca por prestadores de serviço"
    )
    entrada_do_agente_questionador = f"Problema: {problema}\nCidade: {cidade}\nEstado: {estado}"
    # Executa o agente
    pergunta = call_agent(questionador, entrada_do_agente_questionador)
    return pergunta

######################################
# --- Agente 4: Severino Indica --- #
######################################
def agente_indicador(problema, indicacoes):
    indicador = Agent(
        name="agente_indicador",
        model="gemini-2.0-flash",
        tools = [google_search],
        instruction="""
            Você é um Marido de Aluguel que acabou de pesquisar prestadores de serviço que podem solucionar o problema pesquisado pelo usuário.
            Utilizando a tools (google_search), você deverá analisar quais prestadores são mais relevantes com base
            na quantidade de avaliações e da nota. Caso os prestadores de serviço encontrados não possuam avaliações, considerar os
            resultados por ordem de exibição na tools (google_search).
            Você deverá informar ao usuário o nome do prestador de serviço / empresa, o endereço e o telefone. Listas apenas 3 opções.
            """,
        description="Agente Marido de Aluguel que indica prestadores de serviço"
    )
    entrada_do_agente_indicador = f"Problema: {problema}\nIndicações: {indicacoes}"
    # Executa o agente
    indicacao = call_agent(indicador, entrada_do_agente_indicador)
    return indicacao

data_de_hoje = date.today().strftime("%d/%m/%Y")

# --- Obter o Problema do Usuário ---
problema = input("❓ Por favor, digite qual problema ou dificuldade você está enfrentando. ")

# Inserir lógica do sistema de agentes ################################################

if not problema:
  print("Você ainda não me contou com o que precisa de ajuda!")
else:
  print(f"Maravilha! Deixa comigo que já te digo o que fazer!")

problemas_buscados = agente_buscador(problema, data_de_hoje)
#print("\n--- Resultados do Agente 1 ---\n")
#display(to_markdown(problemas_buscados))
#print("----------------------1------------------------")

melhor_solucao = agente_severino(problema, problemas_buscados)
#print("\n--- Resultados do Agente 3 ---\n")
display(to_markdown(melhor_solucao))
#print("---------------------2-------------------------")

# --- Obter Cidade/Estado do Usuário ---
cidade = input("❓ Por favor, informe sua Cidade: ")

if not cidade:
  print("Preciso que me diga o nome da sua cidade para buscar por profissionais que te ajudem!")
else:
  print(f"Muito obrigado")

estado = input("❓ Agora, por favor, informe seu Estado: ")

if not estado:
  print("Preciso que me diga o nome do seu estado para buscar por profissionais que te ajudem!")
else:
  print("Perfeito, deixe-me buscar pelos profissionais.")

avaliacoes = agente_questionador(problema, cidade, estado)
#print("\n--- Resultados do Agente 2 ---\n")
#display(to_markdown(avaliacoes))
#print("----------------------------------------------")

profissionais = agente_indicador(problema, avaliacoes)
print("\n--- Seguem alguns dos profissionais melhor avaliados na sua cidade ---\n")
display(to_markdown(profissionais))
print("----------------------------------------------")

# prompt: Gere uma interface integrada aos agentes desenvolvidos acima. A interface deve conter uma tag H1, uma tag de imagem, label, input e botão. O código deve permitir a estilização dos elementos, contudo, a interface não deve exibir as opções de estilização.

from IPython.display import display, HTML
import ipywidgets as widgets
from IPython.display import clear_output

# Container para a interface (para aplicar estilos)
interface_container = widgets.Output()

def on_button_click(b):
    with interface_container:
        clear_output()  # Limpa a saída anterior
        user_problema = problema_input.value
        user_cidade = cidade_input.value
        user_estado = estado_input.value

        display(HTML('<h1>Marido de Aluguel Digital</h1>'))
        display(HTML('<img src="https://www.suacasarenovada.com.br/wp-content/uploads/2018/06/Marido-de-Aluguel.jpg" alt="Marido de Aluguel" style="width:200px;height:auto;">'))

        if not user_problema:
            print("❓ Por favor, digite qual problema ou dificuldade você está enfrentando.")
            return
        else:
            print(f"Maravilha! Deixa comigo que já te digo o que fazer!")

        data_de_hoje = date.today().strftime("%d/%m/%Y")

        # Executa a lógica dos agentes
        problemas_buscados = agente_buscador(user_problema, data_de_hoje)
        melhor_solucao = agente_severino(user_problema, problemas_buscados)
        display(to_markdown(melhor_solucao))

        if not user_cidade:
            print("Preciso que me diga o nome da sua cidade para buscar por profissionais que te ajudem!")
            return
        else:
            print(f"Muito obrigado")

        if not user_estado:
            print("Preciso que me diga o nome do seu estado para buscar por profissionais que te ajudem!")
            return
        else:
            print("Perfeito, deixe-me buscar pelos profissionais.")

        avaliacoes = agente_questionador(user_problema, user_cidade, user_estado)
        profissionais = agente_indicador(user_problema, avaliacoes)
        print("\n--- Seguem alguns dos profissionais melhor avaliados na sua cidade ---\n")
        display(to_markdown(profissionais))


# Cria os widgets
h1_tag = HTML('<h1>Agente Severino</h1>')
img_tag = HTML('<img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgaXi1jk5XKKgbiZWDrucB7XEIdeh7yb9OfSpdHDHHlzh4UWzet-9P1ITLgf-G2zmQwQTYWEf3kXNHSutda0n2ChkdrfewmW_ZeAt4tzRO8pT0CP6-N-3maMNcGFD9jaDttPttxs5HpNA7_3lYL8kvIONQU9sEyNkxsXo8W49M08qgqW_xG5HL9Zx7-tKq0/s320/severino.png" alt="Marido de Aluguel" style="width:200px;height:auto;">')

problema_label = widgets.Label("❓ Qual problema ou dificuldade você está enfrentando.")
problema_input = widgets.Text()

cidade_label = widgets.Label("❓ Qual sua Cidade?")
cidade_input = widgets.Text()

estado_label = widgets.Label("❓ Qual seu Estado?")
estado_input = widgets.Text()

send_button = widgets.Button(description="Buscar Solução")
send_button.on_click(on_button_click)

# Exibe os elementos na interface_container
with interface_container:
    display(h1_tag)
    display(img_tag)
    display(problema_label)
    display(problema_input)
    display(cidade_label)
    display(cidade_input)
    display(estado_label)
    display(estado_input)
    display(send_button)

# Exibe o container que contém a interface
display(interface_container)